///////////////////////////////////////////////////////////
//  LongDateConverter.cs
//  Implementation of the Class LongDateConverter
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2009 5:33:41 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using System;
using System.Globalization;
using System.Windows.Data;
namespace SilverlightTemps.ValueConverters {
	public class LongDateConverter : IValueConverter {

		/// 
		/// <param name="value"></param>
		/// <param name="targetType"></param>
		/// <param name="parameter"></param>
		/// <param name="culture"></param>
		public Object Convert(Object value, Type targetType, Object parameter, CultureInfo culture){

            return ((DateTime)value).ToString("MMMM d, yyyy");
		}

		/// 
		/// <param name="value"></param>
		/// <param name="targetType"></param>
		/// <param name="parameter"></param>
		/// <param name="culture"></param>
		public Object ConvertBack(Object value, Type targetType, Object parameter, CultureInfo culture){

            return DateTime.Parse(value.ToString());
		}

	}//end LongDateConverter

}//end namespace ValueConverters