///////////////////////////////////////////////////////////
//  DateTemperatureRange.cs
//  Implementation of the Class DateTemperatureRange
//  Generated by Enterprise Architect
//  Created on:      05-Feb-2009 9:11:41 AM
//  Original author: Gary
///////////////////////////////////////////////////////////




using System;
using Bortosky.Samples.Temperature.Data;
namespace Bortosky.Samples.Temperature.Data {
	public class DateTemperatureRange {

        public TemperatureRange Range { get; set; }
        public DateTime RangeDateTime { get; set; }

		/// 
		/// <param name="range"></param>
		/// <param name="date"></param>
        public DateTemperatureRange(TemperatureRange range, DateTime date)
        {
            this.Range = range;
            this.RangeDateTime = date;
        }

		/// 
		/// <param name="obj"></param>
        public override bool Equals(object obj)
        {
            var dtr = obj as DateTemperatureRange;
            return this.RangeDateTime.Equals(dtr.RangeDateTime) && this.Range.Equals(dtr.Range);
        }

        public override int GetHashCode()
        {
            return this.Range.GetHashCode() + this.RangeDateTime.GetHashCode();
        }

	}//end DateTemperatureRange

}//end namespace Data