///////////////////////////////////////////////////////////
//  IDataService.cs
//  Implementation of the Interface IDataService
//  Generated by Enterprise Architect
//  Created on:      05-Feb-2009 9:11:45 AM
//  Original author: Gary
///////////////////////////////////////////////////////////




using System.Collections.Generic;
using System;
namespace Bortosky.Samples.Temperature.Data {
	public interface IDataService {

		/// <summary>
		/// Gets a sequential list of DateTemperatureRanges starting with the specified
		/// date containing the given number of days. The number returned may not actually
		/// equal the requested number if days are missing from the data source.
		/// </summary>
		/// <param name="date">The start date of the range requested. The date of the first
		/// DateTemperatureRange returned will be >= this date.</param>
		/// <param name="days">The days after the start date to return.  The date of the
		/// last DateTemperatureRange returned will be <= the start date plus this value.
		/// </param>
		List<DateTemperatureRange> GetTemperaturesByDate(string stationId, DateTime date, int days);

		/// <summary>
		/// Returns a DateTemperatureRange for each day of the requested month
		/// </summary>
		/// <param name="year">The year part of the month whose temeprature ranges are
		/// requested</param>
		/// <param name="month">The month in the given year whose temperature ranges are
		/// requested</param>
		List<DateTemperatureRange> GetTemperaturesByMonth(string stationId, int year, int month);
	}//end IDataService

}//end namespace Data