///////////////////////////////////////////////////////////
//  TemperatureRange.cs
//  Implementation of the Class TemperatureRange
//  Generated by Enterprise Architect
//  Created on:      05-Feb-2009 9:11:38 AM
//  Original author: Gary
///////////////////////////////////////////////////////////




namespace Bortosky.Samples.Temperature.Data {
	/// <summary>
	/// A range of temperatures
	/// </summary>
	public class TemperatureRange {

        public float Max { get; set; }
        public float Min { get; set; }

		/// 
		/// <param name="min"></param>
		/// <param name="max"></param>
        public TemperatureRange(float min, float max)
        {
            this.Max = max;
            this.Min = min;
        }

		/// 
		/// <param name="obj"></param>
		public override bool Equals(object obj){
            var o = obj as TemperatureRange;
            return this.Max.Equals(o.Max) && this.Min.Equals(o.Min);
		}

        public override int GetHashCode()
        {
            return this.Max.GetHashCode() + this.Min.GetHashCode();
        }
        public override string ToString()
        {
            return string.Format("Maximum: {0}, Minimum {1}", this.Max, this.Min);
        }

	}//end TemperatureRange

}//end namespace Data