///////////////////////////////////////////////////////////
//  MockTemperatureDataService.cs
//  Implementation of the Class MockTemperatureDataService
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2009 7:55:01 PM
//  Original author: Gary
///////////////////////////////////////////////////////////



using System;
using System.Collections.Generic;
using SilverlightTemps.DataService;
namespace SilverlightTemps.DataService {
	public class MockTemperatureDataService : TemperatureDataService {


		/// 
		/// <param name="stationId"></param>
		/// <param name="days"></param>
        public override void GetRecentTemperaturesAsync(string stationId, int days)
        {
            List<TemperatureDay> d = new List<TemperatureDay>();
            d.Add(new TemperatureDay() { MaxTemperature = 79, MinTemperature = 49, SubjectDate = new DateTime(2007, 1, 1) });
            d.Add(new TemperatureDay() { MaxTemperature = 62, MinTemperature = 41, SubjectDate = new DateTime(2007, 1, 2) });
            d.Add(new TemperatureDay() { MaxTemperature = 58, MinTemperature = 33, SubjectDate = new DateTime(2007, 1, 3) });
            d.Add(new TemperatureDay() { MaxTemperature = 97, MinTemperature = 73, SubjectDate = new DateTime(2007, 1, 4) });
            d.Add(new TemperatureDay() { MaxTemperature = 62.99F, MinTemperature = 34, SubjectDate = new DateTime(2007, 1, 5) });
            d.Add(new TemperatureDay() { MaxTemperature = 73, MinTemperature = 50, SubjectDate = new DateTime(2007, 1, 6) });
            d.Add(new TemperatureDay() { MaxTemperature = 81, MinTemperature = 58, SubjectDate = new DateTime(2007, 1, 7) });
            d.Add(new TemperatureDay() { MaxTemperature = 62, MinTemperature = 39, SubjectDate = new DateTime(2007, 1, 8) });
            d.Add(new TemperatureDay() { MaxTemperature = 50, MinTemperature = 21, SubjectDate = new DateTime(2007, 1, 9) });
            d.Add(new TemperatureDay() { MaxTemperature = 79, MinTemperature = 50, SubjectDate = new DateTime(2007, 1, 10) });
            d.Add(new TemperatureDay() { MaxTemperature = 64, MinTemperature = 40, SubjectDate = new DateTime(2007, 1, 11) });
            d.Add(new TemperatureDay() { MaxTemperature = 83, MinTemperature = 56, SubjectDate = new DateTime(2007, 1, 12) });
            d.Add(new TemperatureDay() { MaxTemperature = 97, MinTemperature = 73, SubjectDate = new DateTime(2007, 1, 13) });
            d.Add(new TemperatureDay() { MaxTemperature = 95, MinTemperature = 65, SubjectDate = new DateTime(2007, 1, 14) });
            d.Add(new TemperatureDay() { MaxTemperature = 89, MinTemperature = 69, SubjectDate = new DateTime(2007, 1, 15) });
            d.Add(new TemperatureDay() { MaxTemperature = 57, MinTemperature = 33, SubjectDate = new DateTime(2007, 1, 16) });
            d.Add(new TemperatureDay() { MaxTemperature = 59, MinTemperature = 29, SubjectDate = new DateTime(2007, 1, 17) });
            d.Add(new TemperatureDay() { MaxTemperature = 86, MinTemperature = 62, SubjectDate = new DateTime(2007, 1, 18) });
            d.Add(new TemperatureDay() { MaxTemperature = 65, MinTemperature = 44, SubjectDate = new DateTime(2007, 1, 19) });
            d.Add(new TemperatureDay() { MaxTemperature = 78, MinTemperature = 54, SubjectDate = new DateTime(2007, 1, 20) });
            d.Add(new TemperatureDay() { MaxTemperature = 89, MinTemperature = 65, SubjectDate = new DateTime(2007, 1, 21) });
            d.Add(new TemperatureDay() { MaxTemperature = 91, MinTemperature = 63, SubjectDate = new DateTime(2007, 1, 22) });
            d.Add(new TemperatureDay() { MaxTemperature = 52, MinTemperature = 25, SubjectDate = new DateTime(2007, 1, 23) });
            d.Add(new TemperatureDay() { MaxTemperature = 90, MinTemperature = 63, SubjectDate = new DateTime(2007, 1, 24) });
            d.Add(new TemperatureDay() { MaxTemperature = 92, MinTemperature = 67, SubjectDate = new DateTime(2007, 1, 25) });
            d.Add(new TemperatureDay() { MaxTemperature = 65, MinTemperature = 42, SubjectDate = new DateTime(2007, 1, 26) });
            d.Add(new TemperatureDay() { MaxTemperature = 68, MinTemperature = 44, SubjectDate = new DateTime(2007, 1, 27) });
            d.Add(new TemperatureDay() { MaxTemperature = 68, MinTemperature = 42, SubjectDate = new DateTime(2007, 1, 28) });
            d.Add(new TemperatureDay() { MaxTemperature = 70, MinTemperature = 41, SubjectDate = new DateTime(2007, 1, 29) });
            d.Add(new TemperatureDay() { MaxTemperature = 87, MinTemperature = 62, SubjectDate = new DateTime(2007, 1, 30) });
            d.Add(new TemperatureDay() { MaxTemperature = 59, MinTemperature = 39, SubjectDate = new DateTime(2007, 1, 31) });
            d.Add(new TemperatureDay() { MaxTemperature = 71, MinTemperature = 41, SubjectDate = new DateTime(2007, 2, 1) });
            d.Add(new TemperatureDay() { MaxTemperature = 97, MinTemperature = 74, SubjectDate = new DateTime(2007, 2, 2) });
            d.Add(new TemperatureDay() { MaxTemperature = 96, MinTemperature = 72, SubjectDate = new DateTime(2007, 2, 3) });
            d.Add(new TemperatureDay() { MaxTemperature = 68, MinTemperature = 48, SubjectDate = new DateTime(2007, 2, 4) });
            d.Add(new TemperatureDay() { MaxTemperature = 78, MinTemperature = 50, SubjectDate = new DateTime(2007, 2, 5) });
            d.Add(new TemperatureDay() { MaxTemperature = 81, MinTemperature = 60, SubjectDate = new DateTime(2007, 2, 6) });
            d.Add(new TemperatureDay() { MaxTemperature = 83, MinTemperature = 57, SubjectDate = new DateTime(2007, 2, 7) });
            d.Add(new TemperatureDay() { MaxTemperature = 89, MinTemperature = 68, SubjectDate = new DateTime(2007, 2, 8) });
            d.Add(new TemperatureDay() { MaxTemperature = 82, MinTemperature = 61, SubjectDate = new DateTime(2007, 2, 9) });
            d.Add(new TemperatureDay() { MaxTemperature = 50, MinTemperature = 40, SubjectDate = new DateTime(2007, 2, 10) });
            d.Add(new TemperatureDay() { MaxTemperature = 60, MinTemperature = 30, SubjectDate = new DateTime(2007, 2, 11) });
            d.Add(new TemperatureDay() { MaxTemperature = 70, MinTemperature = 20, SubjectDate = new DateTime(2007, 2, 12) });
            d.Add(new TemperatureDay() { MaxTemperature = 80, MinTemperature = 10, SubjectDate = new DateTime(2007, 2, 13) });
            d.Add(new TemperatureDay() { MaxTemperature = 90, MinTemperature = 0, SubjectDate = new DateTime(2007, 2, 14) });
            d.Add(new TemperatureDay() { MaxTemperature = 100, MinTemperature = -10, SubjectDate = new DateTime(2007, 2, 15) });
            d.Add(new TemperatureDay() { MaxTemperature = 110, MinTemperature = -20, SubjectDate = new DateTime(2007, 2, 16) });
            d.Add(new TemperatureDay() { MaxTemperature = 57, MinTemperature = 37, SubjectDate = new DateTime(2007, 2, 17) });
            d.Add(new TemperatureDay() { MaxTemperature = 58, MinTemperature = 30, SubjectDate = new DateTime(2005, 1, 5) });
            d.Add(new TemperatureDay() { MaxTemperature = 70, MinTemperature = 40, SubjectDate = new DateTime(2006, 1, 5) });
            OnGetRecentTemperaturesComplete(d);
        }

	}//end MockTemperatureDataService

}//end namespace DataService