///////////////////////////////////////////////////////////
//  TemperatureDataEventArgs.cs
//  Implementation of the Class TemperatureDataEventArgs
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2009 7:29:54 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using System.Collections.Generic;
using System;
namespace SilverlightTemps.DataService
{
    public class TemperatureDataEventArgs : EventArgs
    {

        public List<TemperatureDay> TemperatureDays
        {
            get { return this.temperatureDays; }
        }
        private List<TemperatureDay> temperatureDays;

        /// 
        /// <param name="tempDays"></param>
        public TemperatureDataEventArgs(List<TemperatureDay> tempDays)
        {
            this.temperatureDays = tempDays;
        }

    }//end TemperatureDataEventArgs

}//end namespace DataService