///////////////////////////////////////////////////////////
//  Location.cs
//  Implementation of the Class Location
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////



using System.ServiceModel;
using System.Runtime.Serialization;
namespace Bortosky.Samples.RetailChain.Client.Data
{
    [DataContract]
    public class Location
    {
        [DataMember]
        public string Street { get; set; }
        [DataMember]
        public string City { get; set; }
        [DataMember]
        public string State { get; set; }
        [DataMember]
        public string ZIP { get; set; }
        [DataMember]
        public float Longitude { get; set; }
        [DataMember]
        public float Latitude { get; set; }

    }//end Location

}//end namespace Data