///////////////////////////////////////////////////////////
//  Store.cs
//  Implementation of the Class Store
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////


using System.ServiceModel;
using System.Runtime.Serialization;
using Bortosky.Samples.RetailChain.Client.Data;
namespace Bortosky.Samples.RetailChain.Client.Data
{
    [DataContract]
    public class Store
    {
        [DataMember]
        public string Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public Location Location { get; set; }
    }//end Store

}//end namespace Data