///////////////////////////////////////////////////////////
//  Store.cs
//  Implementation of the Class Store
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using Bortosky.Samples.RetailChain.Client.Data;
namespace Bortosky.Samples.RetailChain.Client.Data
{
    public class Store
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Location Location { get; set; }
    }//end Store

}//end namespace Data