///////////////////////////////////////////////////////////
//  MockTemperatureDataService.cs
//  Implementation of the Class MockTemperatureDataService
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2009 7:55:01 PM
//  Original author: Gary
///////////////////////////////////////////////////////////



using System;
using System.Collections.Generic;
using SilverlightTemps.DataService;
namespace SilverlightTemps.DataService {
	public class MockTemperatureDataService : TemperatureDataService {


		/// 
		/// <param name="stationId"></param>
		/// <param name="days"></param>
        public override void GetRecentTemperaturesAsync(string stationId, int days)
        {
            List<TemperatureDay> d = new List<TemperatureDay>();
            d.Add(new TemperatureDay() { MaxTemperature = 75F, MinTemperature = 48.9F, SubjectDate = new DateTime(2008, 11, 1) });
            d.Add(new TemperatureDay() { MaxTemperature = 75.9F, MinTemperature = 48.9F, SubjectDate = new DateTime(2008, 11, 2) });
            d.Add(new TemperatureDay() { MaxTemperature = 77F, MinTemperature = 52F, SubjectDate = new DateTime(2008, 11, 3) });
            d.Add(new TemperatureDay() { MaxTemperature = 77F, MinTemperature = 48F, SubjectDate = new DateTime(2008, 11, 4) });
            d.Add(new TemperatureDay() { MaxTemperature = 75.2F, MinTemperature = 55.4F, SubjectDate = new DateTime(2008, 11, 5) });
            d.Add(new TemperatureDay() { MaxTemperature = 75F, MinTemperature = 55.9F, SubjectDate = new DateTime(2008, 11, 6) });
            d.Add(new TemperatureDay() { MaxTemperature = 68F, MinTemperature = 42.1F, SubjectDate = new DateTime(2008, 11, 7) });
            d.Add(new TemperatureDay() { MaxTemperature = 52F, MinTemperature = 37F, SubjectDate = new DateTime(2008, 11, 8) });
            d.Add(new TemperatureDay() { MaxTemperature = 44.1F, MinTemperature = 34F, SubjectDate = new DateTime(2008, 11, 9) });
            d.Add(new TemperatureDay() { MaxTemperature = 42.8F, MinTemperature = 26.6F, SubjectDate = new DateTime(2008, 11, 10) });
            d.Add(new TemperatureDay() { MaxTemperature = 50F, MinTemperature = 27.1F, SubjectDate = new DateTime(2008, 11, 11) });
            d.Add(new TemperatureDay() { MaxTemperature = 57.9F, MinTemperature = 39F, SubjectDate = new DateTime(2008, 11, 12) });
            d.Add(new TemperatureDay() { MaxTemperature = 63F, MinTemperature = 42.1F, SubjectDate = new DateTime(2008, 11, 13) });
            d.Add(new TemperatureDay() { MaxTemperature = 63F, MinTemperature = 42.1F, SubjectDate = new DateTime(2008, 11, 14) });
            d.Add(new TemperatureDay() { MaxTemperature = 50F, MinTemperature = 35.6F, SubjectDate = new DateTime(2008, 11, 15) });
            d.Add(new TemperatureDay() { MaxTemperature = 57F, MinTemperature = 30F, SubjectDate = new DateTime(2008, 11, 16) });
            d.Add(new TemperatureDay() { MaxTemperature = 57F, MinTemperature = 31.1F, SubjectDate = new DateTime(2008, 11, 17) });
            d.Add(new TemperatureDay() { MaxTemperature = 37.9F, MinTemperature = 24.8F, SubjectDate = new DateTime(2008, 11, 18) });
            d.Add(new TemperatureDay() { MaxTemperature = 59F, MinTemperature = 26.2F, SubjectDate = new DateTime(2008, 11, 19) });
            d.Add(new TemperatureDay() { MaxTemperature = 59F, MinTemperature = 33.1F, SubjectDate = new DateTime(2008, 11, 20) });
            d.Add(new TemperatureDay() { MaxTemperature = 33.1F, MinTemperature = 19.4F, SubjectDate = new DateTime(2008, 11, 21) });
            d.Add(new TemperatureDay() { MaxTemperature = 37.4F, MinTemperature = 21.2F, SubjectDate = new DateTime(2008, 11, 22) });
            d.Add(new TemperatureDay() { MaxTemperature = 51.8F, MinTemperature = 21.2F, SubjectDate = new DateTime(2008, 11, 23) });
            d.Add(new TemperatureDay() { MaxTemperature = 51.8F, MinTemperature = 44.6F, SubjectDate = new DateTime(2008, 11, 24) });
            d.Add(new TemperatureDay() { MaxTemperature = 53.1F, MinTemperature = 28F, SubjectDate = new DateTime(2008, 11, 25) });
            d.Add(new TemperatureDay() { MaxTemperature = 55F, MinTemperature = 26.1F, SubjectDate = new DateTime(2008, 11, 26) });
            d.Add(new TemperatureDay() { MaxTemperature = 57F, MinTemperature = 27.1F, SubjectDate = new DateTime(2008, 11, 27) });
            d.Add(new TemperatureDay() { MaxTemperature = 57F, MinTemperature = 30.2F, SubjectDate = new DateTime(2008, 11, 28) });
            d.Add(new TemperatureDay() { MaxTemperature = 50F, MinTemperature = 37.9F, SubjectDate = new DateTime(2008, 11, 29) });
            d.Add(new TemperatureDay() { MaxTemperature = 46F, MinTemperature = 33.1F, SubjectDate = new DateTime(2008, 11, 30) });
            d.Add(new TemperatureDay() { MaxTemperature = 36F, MinTemperature = 28F, SubjectDate = new DateTime(2008, 12, 1) });
            d.Add(new TemperatureDay() { MaxTemperature = 48.2F, MinTemperature = 26.1F, SubjectDate = new DateTime(2008, 12, 2) });
            d.Add(new TemperatureDay() { MaxTemperature = 48.9F, MinTemperature = 26.2F, SubjectDate = new DateTime(2008, 12, 3) });
            d.Add(new TemperatureDay() { MaxTemperature = 33.8F, MinTemperature = 19F, SubjectDate = new DateTime(2008, 12, 4) });
            d.Add(new TemperatureDay() { MaxTemperature = 30.2F, MinTemperature = 15.8F, SubjectDate = new DateTime(2008, 12, 5) });
            d.Add(new TemperatureDay() { MaxTemperature = 45F, MinTemperature = 17.1F, SubjectDate = new DateTime(2008, 12, 6) });
            d.Add(new TemperatureDay() { MaxTemperature = 45F, MinTemperature = 15.1F, SubjectDate = new DateTime(2008, 12, 7) });
            d.Add(new TemperatureDay() { MaxTemperature = 53.6F, MinTemperature = 28F, SubjectDate = new DateTime(2008, 12, 8) });
            d.Add(new TemperatureDay() { MaxTemperature = 55.4F, MinTemperature = 33.8F, SubjectDate = new DateTime(2008, 12, 9) });
            d.Add(new TemperatureDay() { MaxTemperature = 34F, MinTemperature = 24.8F, SubjectDate = new DateTime(2008, 12, 10) });
            d.Add(new TemperatureDay() { MaxTemperature = 39F, MinTemperature = 21.9F, SubjectDate = new DateTime(2008, 12, 11) });
            d.Add(new TemperatureDay() { MaxTemperature = 42.1F, MinTemperature = 23.2F, SubjectDate = new DateTime(2008, 12, 12) });
            d.Add(new TemperatureDay() { MaxTemperature = 48.9F, MinTemperature = 30.9F, SubjectDate = new DateTime(2008, 12, 13) });
            d.Add(new TemperatureDay() { MaxTemperature = 57F, MinTemperature = 33.1F, SubjectDate = new DateTime(2008, 12, 14) });
            d.Add(new TemperatureDay() { MaxTemperature = 57F, MinTemperature = 12.2F, SubjectDate = new DateTime(2008, 12, 15) });
            d.Add(new TemperatureDay() { MaxTemperature = 28.9F, MinTemperature = 14F, SubjectDate = new DateTime(2008, 12, 16) });
            d.Add(new TemperatureDay() { MaxTemperature = 26.6F, MinTemperature = 19.4F, SubjectDate = new DateTime(2008, 12, 17) });
            d.Add(new TemperatureDay() { MaxTemperature = 32F, MinTemperature = 21F, SubjectDate = new DateTime(2008, 12, 18) });
            d.Add(new TemperatureDay() { MaxTemperature = 55F, MinTemperature = 23F, SubjectDate = new DateTime(2008, 12, 19) });
            d.Add(new TemperatureDay() { MaxTemperature = 35.6F, MinTemperature = 28.4F, SubjectDate = new DateTime(2008, 12, 20) });
            d.Add(new TemperatureDay() { MaxTemperature = 37F, MinTemperature = 6.1F, SubjectDate = new DateTime(2008, 12, 21) });
            d.Add(new TemperatureDay() { MaxTemperature = 19.4F, MinTemperature = 3.2F, SubjectDate = new DateTime(2008, 12, 22) });
            d.Add(new TemperatureDay() { MaxTemperature = 35.6F, MinTemperature = 19F, SubjectDate = new DateTime(2008, 12, 23) });
            d.Add(new TemperatureDay() { MaxTemperature = 42.1F, MinTemperature = 21.9F, SubjectDate = new DateTime(2008, 12, 24) });
            d.Add(new TemperatureDay() { MaxTemperature = 33.8F, MinTemperature = 15.8F, SubjectDate = new DateTime(2008, 12, 25) });
            d.Add(new TemperatureDay() { MaxTemperature = 61F, MinTemperature = 17.1F, SubjectDate = new DateTime(2008, 12, 26) });
            d.Add(new TemperatureDay() { MaxTemperature = 68F, MinTemperature = 55.4F, SubjectDate = new DateTime(2008, 12, 27) });
            d.Add(new TemperatureDay() { MaxTemperature = 68F, MinTemperature = 30F, SubjectDate = new DateTime(2008, 12, 28) });
            d.Add(new TemperatureDay() { MaxTemperature = 57F, MinTemperature = 31.1F, SubjectDate = new DateTime(2008, 12, 29) });
            d.Add(new TemperatureDay() { MaxTemperature = 66F, MinTemperature = 28.9F, SubjectDate = new DateTime(2008, 12, 30) });
            d.Add(new TemperatureDay() { MaxTemperature = 53.1F, MinTemperature = 21.2F, SubjectDate = new DateTime(2008, 12, 31) });
            OnGetRecentTemperaturesComplete(d);
        }

	}//end MockTemperatureDataService

}//end namespace DataService