///////////////////////////////////////////////////////////
//  SoapTemperatureDataService.cs
//  Implementation of the Class SoapTemperatureDataService
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2009 8:46:40 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using SilverlightTemps.DataService;
namespace SilverlightTemps.DataService {
	public class SoapTemperatureDataService : TemperatureDataService {

		/// 
		/// <param name="stationId"></param>
		/// <param name="days"></param>
		public override void GetRecentTemperaturesAsync(string stationId, int days){

		}

	}//end SoapTemperatureDataService

}//end namespace DataService