//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Bortosky.Samples.Temperature.DataService.DataLayer {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bortosky.com/temperature")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bortosky.com/temperature", IsNullable=false)]
    public partial class TemperatureResponse {
        
        private DateRangeType[] dateRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateRange")]
        public DateRangeType[] DateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bortosky.com/temperature")]
    public partial class DateRangeType {
        
        private string rangeDateField;
        
        private TemperatureRangeType rangeField;
        
        /// <remarks/>
        public string RangeDate {
            get {
                return this.rangeDateField;
            }
            set {
                this.rangeDateField = value;
            }
        }
        
        /// <remarks/>
        public TemperatureRangeType Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bortosky.com/temperature")]
    public partial class TemperatureRangeType {
        
        private float maximumField;
        
        private float minimumField;
        
        /// <remarks/>
        public float Maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
        
        /// <remarks/>
        public float Minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
    }
}
