///////////////////////////////////////////////////////////
//  TemperatureTextConverter.cs
//  Implementation of the Class TemperatureTextConverter
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2009 5:39:02 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using System;
using System.Globalization;
using System.Windows.Data;
namespace SilverlightTemps.ValueConverters {
	public class TemperatureTextConverter : IValueConverter {

		/// 
		/// <param name="value"></param>
		/// <param name="targetType"></param>
		/// <param name="parameter"></param>
		/// <param name="culture"></param>
		public Object Convert(Object value, Type targetType, Object parameter, CultureInfo culture){

            return string.Format("{0:N0}°", value);
		}

		/// 
		/// <param name="value"></param>
		/// <param name="targetType"></param>
		/// <param name="parameter"></param>
		/// <param name="culture"></param>
		public Object ConvertBack(Object value, Type targetType, Object parameter, CultureInfo culture){

			return null;
		}

	}//end TemperatureTextConverter

}//end namespace ValueConverters