///////////////////////////////////////////////////////////
//  Brand.cs
//  Implementation of the Class Brand
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




namespace Bortosky.Samples.RetailChain.Client.Data {
    public class Brand
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }

    }//end Brand

}//end namespace Data