///////////////////////////////////////////////////////////
//  Brand.cs
//  Implementation of the Class Brand
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////



using System.ServiceModel;
using System.Runtime.Serialization;
namespace Bortosky.Samples.RetailChain.Client.Data
{
    [DataContract]
    public class Brand
    {
        [DataMember]
        public string Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Color { get; set; }

    }//end Brand

}//end namespace Data