///////////////////////////////////////////////////////////
//  IRetailerService.cs
//  Implementation of the Interface IRetailerService
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using System.Collections.Generic;
namespace Bortosky.Samples.RetailChain.Client.Data {
	public interface IRetailerService {

		IEnumerable<Store> GetStores();

		/// 
		/// <param name="storeId"></param>
		/// <param name="week"></param>
		IEnumerable<WeeklySale> GetWeeklySales(string storeId, string week);

		/// 
		/// <param name="storeId"></param>
		Store GetStore(string storeId);
	}//end IRetailerService

}//end namespace Data