///////////////////////////////////////////////////////////
//  WeeklySale.cs
//  Implementation of the Class WeeklySale
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using Bortosky.Samples.RetailChain.Client.Data;
namespace Bortosky.Samples.RetailChain.Client.Data
{
    public class WeeklySale
    {
        public string ISOWeek { get; set; }
        public float GrossAmount { get; set; }
        public Brand Brand { get; set; }
        public Store Store { get; set; }

    }//end WeeklySale

}//end namespace Data