///////////////////////////////////////////////////////////
//  WeeklySale.cs
//  Implementation of the Class WeeklySale
//  Generated by Enterprise Architect
//  Created on:      14-Mar-2009 1:56:55 PM
//  Original author: Gary
///////////////////////////////////////////////////////////



using System.ServiceModel;
using System.Runtime.Serialization;
using Bortosky.Samples.RetailChain.Client.Data;
namespace Bortosky.Samples.RetailChain.Client.Data
{
    [DataContract]
    public class WeeklySale
    {
        [DataMember]
        public string ISOWeek { get; set; }
        [DataMember]
        public float GrossAmount { get; set; }
        [DataMember]
        public Brand Brand { get; set; }
        [DataMember]
        public Store Store { get; set; }

    }//end WeeklySale

}//end namespace Data