///////////////////////////////////////////////////////////
//  TemperatureDay.cs
//  Implementation of the Class TemperatureDay
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2009 7:00:34 PM
//  Original author: Gary
///////////////////////////////////////////////////////////




using System;
namespace SilverlightTemps {
	public class TemperatureDay {


		public DateTime SubjectDate{
			get
				;
			
			set
				;
			
		}

		public float MaxTemperature{
			get
				;
			
			set
				;
			
		}

		public float MinTemperature{
			get
				;
			
			set
				;
			
		}

	}//end TemperatureDay

}//end namespace SilverlightTemps